fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: requirements-txt-fixer
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --no-ensure-ascii
          - --no-sort-keys

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        require_serial: true
        args:
          - --in-place
          - --expand-star-imports
          - --remove-all-unused-imports
          - --remove-unused-variables

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        require_serial: true

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        require_serial: true
        types: [ python ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        additional_dependencies:
          - fastapi
          - pydantic

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --exclude=tests

  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.5
    hooks:
      - id: pylint
        args:
          - --rcfile=pyproject.toml
